### Site Settings ###
title               : GokulVSD
description         : Hi, I'm **Gokul Vasudeva** :wave:<br>
                      I enjoy keeping things organised in a cohesive manner, including data about myself. 
                      To that extent, this is my personal website / blog / showcase. I periodically update my blog with new posts, reflecting what I'm up to. 
                      I also use this website as a professional showcase, including keeping an up-to-date resume available, and a list of my personal projects and achievements. <br> <br>
                      Professionally, I'm a Computer Science Engineer, who has loved computers, including everything related to them, ever since I was exposed to them when I was about 10. <br> <br>
                      I treasure experiences new and old, and feel that life is too short to not enjoy the little things, having fun along the way. I have a strong desire to do things right the
                      first time, which requires me to plan things out, and employ foresight, which is a double edged sword. I regularly ponder about philosophy, 
                      science, and our existence. I consider myself to be an optimistic realist, with a good sense of humour. <br> <br>
                      In terms of my career aspirations, my ideal career trajectory would have me working in the intersection of highly scalable distributed systems, backend engineering, and production Machine Learning.
baseurl             : ""


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Gokul Vasudeva
  email             : gokul.vasda@gmail.com
  github            : GokulVSD
  linkedin          : gokulvsd
  twitter           : GokulVSD
  facebook          : gokul.vsd
  instagram         : gokulvsd
  youtube           : GokulVSD1


### Posts ###
permalink: /blog/:title

### Certificates ###
permalink: /certificates/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  certificates:
    output: true
    permalink: /certificates/:title



### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "certificates"
    values:
      comments: false
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
