### Site Settings ###
title               : GokulVSD - blog & website - Gokul Vasudeva
tagline             : Everything to do with Gokul Vasudeva
description         : All about Gokul Vasudeva, including his blog, projects, achievements, resume and social links
url                 : https://gokulvsd.github.io
baseurl             : ""


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Gokul Vasudeva
  email             : gokul.vasda@gmail.com
  github            : GokulVSD
  linkedin          : gokulvsd
  twitter           : GokulVSD
  facebook          : gokul.vsd
  instagram         : gokulvsd
  youtube           : GokulVSD1


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  certificates:
    output: true
    permalink: /certificates/:title



### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "certificates"
    values:
      comments: false
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
