### Site Settings ###
title               : GokulVSD
tagline             : Blog & Website
description         : Personal website - all about Gokul Vasudeva, including his blog, projects, achievements, resume and social links.
url                 : https://gokulvsd.github.io
baseurl             : ""


### Plugins ###
plugins:
  - jemoji
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Gokul Vasudeva
  email             : gokulvsd@icloud.com
  github            : GokulVSD
  linkedin          : gokulvsd
  twitter           : GokulVSD
  facebook          : gokul.vsd
  instagram         : gokulvsd
  youtube           : \@GokulVSD


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  awards:
    output: true
    permalink: /awards/:title



### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "awards"
    values:
      comments: false
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
